### ISSUE TITLE
ip_network() calls IPv4Address.__init__() with a long, not an int. At least in python 2.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [poojaghosh1/ipaddress-py#2]
```
install ipaddress-py with python 2.6.x on multiple linuxen.

$ python
Python 2.6.6 (r266:84292, Dec 27 2010, 00:02:40) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipaddress
>>> ipaddress.ip_network('192.168.0.0/28')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/ipaddress.py", line 118, in ip_network
    address)
ValueError: '192.168.0.0/28' does not appear to be an IPv4 or IPv6 network
>>>

Problem appears to revolve around internal helper functions (e.g. 
_ip_int_from_string()) returning a long value, for reasons that are not 
immediately apparent to me. This then fails the:

    if isinstance(address, int):

test(s). changing those to accept a long, and relying on duck typing, seems to 
get things working again. Patch attached.
```

Original issue reported on code.google.com by `andyw.l...@gmail.com` on 1 Oct 2013 at 5:20

Attachments:
- [ipaddress.patch](https://storage.googleapis.com/google-code-attachments/ipaddress-py/issue-2/comment-0/ipaddress.patch)

**Comment by GoogleCodeExporter** [comment]
```
I am trying to use 1.0.4 of ipaddress.py and I am running into the problem you 
are describing.  I tried applying your patch and all 5 hunks fail.  I looked at 
the source code of the patch file and ipaddress.py and I see why it fails.  I 
am not exactly sure what to do about it, other than ask you for advice.

I am running Python 2.7.3 on Ubuntu 12.04.2 LTS with the 3.2.5-gg1336 kernel.

I'd be honored and delighted to help you fix it.

Many thanks,


Jeff

```

Original comment by `jeffsilverman@google.com` on 3 Apr 2014 at 9:28
